name: twitteranalysis
dependencies:
  - python=3.6
  - pandas=0.24.2
  - numpy=1.16.4
  - pymongo=3.7.2
  - shapely=1.6.4
  - matplotlib=3.1.0
  - seaborn=0.9.0
  - statsmodels=0.9.0
  - ipykernel=5.1.0
  - descartes=1.1.0
  - pip
  - jupyter
  - pip:
    - h3==3.1.0
    - area==1.1.1
    - folium==0.7.0
    - geopandas==0.5.0
    - geojson==2.4.1